apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: astro-academy
  namespace: argocd
spec:
  description: Duas APIs Astro no AWS Academy, sem provisionar infraestrutura AWS
  sourceRepos:
    - https://github.com/Astro-Inter/astro-gitops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: astro-ai
    - server: https://kubernetes.default.svc
      namespace: astro-api
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astro-ai-api-academy
  namespace: argocd
spec:
  project: astro-academy
  source:
    repoURL: https://github.com/Astro-Inter/astro-gitops.git
    targetRevision: main
    path: apps/astro-ai-api/overlays/academy
  destination:
    server: https://kubernetes.default.svc
    namespace: astro-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
