apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astro-api-academy
  namespace: argocd
spec:
  project: astro-academy
  source:
    repoURL: https://github.com/Astro-Inter/astro-gitops.git
    targetRevision: main
    path: apps/astro-api/overlays/academy
  destination:
    server: https://kubernetes.default.svc
    namespace: astro-api
  # Sync manual até existir uma imagem aprovada e os Secrets estarem prontos.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
