apiVersion: v1
kind: ConfigMap
metadata:
  name: astro-api-config
data:
  PORT: "8080"
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=60.0 -XX:InitialRAMPercentage=20.0"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "1"
